### ISSUE TITLE
!appeal Command

### ISSUE THREAD

**Issue by Crowverlay** [ebshimizu/officer-snag#6]
After an Incident Report, users should be able to !appeal <reason> a case and have people vote on it. With enough votes from the jury, Officer Snag will forgive them.

**Comment by ebshimizu** [comment]
proposed functionality: `!appeal` will open the most recent misclick or other incident triggered by the user that initiated the command for an appeal. An embed will be posted and reactions will be added to vote on whether the appeal should pass or not. At the end of the appeal period (5 minutes?), if the appeal passes, the incident is marked as `appealed` and will not count as an incident in aggregates. incidents are only open for appealing within 5 minutes of the event.

implementation status
- [ ] re-structure database format for misclick incidents, including adding flags for `appealed` and `trialed`.
- [ ] `!appeal` command scaffold
- [ ] validate that user has an appealable incident
- [ ] send embed, add relevant reactions, setTimeout for 5 minutes (or whatever the limit is, configurable?)
- [ ] On timeout: count reaction counts. Modify existing embed with results of vote. Mark incident as `trialed` to prevent multiple attempts.
- [ ] On success: amend incident, mark as `appealed`, decrease infraction count by 1.
